update

diff --git a/tel-update b/tel-update
--- a/tel-update
+++ b/tel-update
@@ -89,6 +89,7 @@ shopt -u dotglob # (include dotfiles in cp -r * globbing)
 catch $(cp -rf $TMPDIR/tel-update/bin/* ~/../usr/bin/) # files in ~/../usr/bin are preferred by tel over files in ~/.tel/bin 
 if [ "$user_option" != '--update' ] ; then
 	git clone --quiet -b $branch --depth=1 https://github.com/t-e-l/bootstrap-changes $TMPDIR/tel-update/bootstrap-changes || exit_error 'Failed to download update'
+	#git clone --quiet -b $branch --depth=1 https://github.com/t-e-l/bootstrap-changes $TMPDIR/tel-update/bootstrap-changes || exit_error 'Failed to download update'
 	rm -f $TMPDIR/tel-update/bootstrap-changes/README.md >/dev/null
 	[[ -d ~/bin ]] || mkdir ~/bin
 	catch $(cp -rf $TMPDIR/tel-update/bootstrap-changes/tel/bin/* ~/bin/) 
