testing tel-theme

diff --git a/tel-theme b/tel-theme
--- a/tel-theme
+++ b/tel-theme
@@ -1,7 +1,7 @@
 #!/usr/bin/env bash
-#cd ~/../ 
 FZF_DEFAULT_COMMAND='fd --type f --hidden --follow --exclude .git'
-wallpaper_folder=~/.wallpapers
+wallpaper_folder=~/.tel/theme/active/wallpaper
+themes_folder=~/.tel/theme/inactive/
 
 show_help(){
     printf  "%s\n"\
@@ -9,70 +9,116 @@ show_help(){
             "tel-theme [OPTIONS] [PATTERN]"\
             "__________________________"\
 	    "OPTIONS"\
-           # "  --install-theme   collect your current theme into a package ready for sharing"\
-           # "  --create-theme   collect your current theme into a package ready for sharing"\
-            "  -h   display this help message"\
-            "  -f ~/mywallpaper.jpg  use supplied file"
+            "  -a | --apply		pick + apply a theme from your currently installed themes"\
+            "  -f | --file		auto-gen theme based on an image"\
+            "  -i | --install	   	install a TEL theme.zip file package"\
+            "  -c | --create		collect and package current files into a theme file"\
+            "  -h | --help 		display this help message"
+}
+
+spinner() {
+	# Spinner animation #
+	# line before calling spinner() must spawn bg process: eg echo hi;sleep 2 &;spinner	
+	# show working spinner
+	PID=$!
+	i=1
+	sp="/-\|"
+	echo -n ' '
+	while [ -d /proc/$PID ]
+	do
+		echo -ne "\b${sp:i++%${#sp}:1}"
+		sleep 0.1
+	done
+	echo -ne "\b${CHECK_MARK}" #remove last spinner	
+}
+
+restart_tel(){
+	tel-restart
+	printf "\e[33;5;2m Theme\e[m%s press [Return] to restart + apply changes..\n"
+	read 
+	tel-restart
 }
 
 install_theme(){
-	echo 'this is WIP'
+
+	selected_theme=$(fd --ignore-case --absolute-path --type f | fzf -e --cycle --color=16 --query="$file_search" --prompt="Pick a theme to apply: " --select-1)
+	#selected_theme=$(tel-find -c "TEL theme (.zip) to install:")
+	#unzip theme to 
+	printf "\e[33;5;2m Theme\e[m%s installing theme file: $selected_theme\n"
+	mv -f $selected_theme $themes_folder
+	printf "\e[33;5;2m Theme\e[m%s installed theme: $selected_theme\n"
+	#mkdir $TMPDIR/tel-theme
+	#cd $TMPDIR/tel-theme
 }
 
 create_theme(){
-	mkdir $TEMP/tel-theme
-	cd $TEMP/tel-theme
-	cp ~/.tel/configs/theme.conf .
-	echo 'this is WIP'
+	printf "\e[33;5;2m Theme\e[m%s packaging current files into theme\n"
+	rm -rf $TMPDIR/tel-theme/* > /dev/null 2>&1
+	mkdir -p $TMPDIR/tel-theme/packaging/configs
+	mkdir -p $TMPDIR/tel-theme/packaging/wallpaper
+	mkdir -p $TMPDIR/tel-theme/packaging/termux
+	cd $TMPDIR/tel-theme/packaging
+	cp ~/.tel/theme/active/wallpaper/*.jpg ./wallpaper/
+	cp ~/.tel/configs/theme.conf ./configs/
+	cp ~/.termux/termux.properties ./termux
+	printf "\e[33;5;2m Theme\e[m%s Enter name for new theme: "
+	while [ -z "$new_theme_name" ] ; do
+		read new_theme_name
+	done
+	printf "\e[33;5;2m Theme\e[m%s Enter name of author: "
+	read author_theme_name
+	tar -v -c -z -f $themes_folder/${new_theme_name}.tar.gz . >&/dev/null &
+	spinner
+	printf "\e[33;5;2m Theme\e[m%s finished! \nmoved theme to:themes_folder/${new_theme_name}"
 }
 
+auto_theme(){
+	cd ~
+	if [ -z "$@" ] ; then
+		file_search="$@" 
+	else
+		file_search=".jpg"
+	fi
+	selected_file=$(fd --extension=jpg -e png --follow --absolute-path --hidden --type f | fzf --cycle --color=16 --query="$file_search" --prompt="Pick a image to theme from: " --select-1)
+#	selected_file=$(tel-find -c 'Choose a image to theme from: ')
+	#selected_file=$(pwd)/$selected_file
+	if [ -z $selected_file ] ; then
+	#	echo 'No file chosen - Exiting...'
+		exit 1
+	fi
+	printf "\e[33;5;2m Theme\e[m%s extracting colorscheme from: $selected_file "
+	(wal -i "$selected_file" -n -q -s -t -e || (echo 'failed to get colors from file' ; exit 1)) &
+#	source ~/.cache/wal/colors.sh
+	spinner 
+	#printf "\e[33;5;2m Theme\e[m%s setting wallpaper as: $selected_file\n"
+	mkdir -p ~/.tel/theme/active/wallpaper >/dev/null 2>&1
+	rm -rf ~/.tel/theme/active/wallpaper/* > /dev/null 2>&1
+	cp "$selected_file" ~/.tel/theme/active/wallpaper/
+#	echo -ne "$selected_file" >> ~/.tel/theme/wallpaper
+	touch ~/.tel/theme/.flag
+	# add flag for setting wallpaper on reboot
+	#termux-wallpaper $options "$selected_file" || echo "Couldn't find $selected_file"
+	~/.tel/scripts/apply_colors.sh # copy wal generated cols to ~/.termux/colors.properties
 
-if [ -z $1 ] ; then
-	cd $wallpaper_folder
-	selected_file=$(ls $wallpaper_folder | fzf -e --cycle --color=16 --prompt="Pick a file to theme from:")
-	options='-f'
-else
-	case "$1" in
-		-i | --install-theme)
-		install_theme
-		exit 0
-		;;
-		-c | --create-theme)
-		create_theme
-		#read WAL wallpaper
-		exit 0
-		;;
-#	#	-f | --file) #use file
-#	#	options=$1
-#		selected_file=$2
-#		exit 0
-#		;;
-#		-u | --url) #use url
-#		options=$1
-#		selected_file=$2
-#		exit 0
-#		;;
-		# Display the help message
-		-h | --help)
-		show_help
-		exit 0
-		;;
- 	esac
+	restart_tel
+}
+
+apply_theme(){
+	cd $themes_folder
 	file_search="$@"
-	selected_file=$(fzf -e --cycle --color=16 --query="$file_search" --prompt="Pick a file to theme from: " --select-1)
-	selected_file=$(pwd)/$selected_file
-fi
+	selected_file=$(fd --ignore-case --absolute-path --type f | fzf -e --cycle --color=16 --query="$file_search" --prompt="Pick a theme to apply: " --select-1)
 
-if [ -z $selected_file ] ; then
-#	echo 'No file chosen - Exiting...'
-	exit 1
-else
-	#curr_dir=$(pwd)
-	#wal --preview
-	printf "\e[33;5;2m Theme\e[m%s extracting colorscheme from: $selected_file\n"
-	wal -i "$selected_file" -n -q -s -t -e || (echo 'failed to get colors from file' ; exit 1)
-	source ~/.cache/wal/colors.sh
+	#selected_file=$(tel-find -c 'Choose a image to theme from: ')
+	if [ -z $selected_file ] ; then
+	#	echo 'No file chosen - Exiting...'
+		exit 1
+	fi
+	printf "\e[33;5;2m Theme\e[m%s extracting colorscheme from: $selected_file "
+	(wal -i "$selected_file" -n -q -s -t -e || (echo 'failed to get colors from file' ; exit 1)) & 
+	spinner
+	#source ~/.cache/wal/colors.sh
 
+	printf "\r\e[33;5;2m Theme\e[m%s extracting colorscheme from: $selected_file "
 	#printf "\e[33;5;2m Theme\e[m%s setting wallpaper as: $selected_file\n"
 	rm -rf ~/.tel/theme/wallpaper/* > /dev/null 2>&1
 	cp "$selected_file" ~/.tel/theme/wallpaper/
@@ -80,17 +126,39 @@ else
 	touch ~/.tel/theme/.flag
 	# add flag for setting wallpaper on reboot
 	#termux-wallpaper $options "$selected_file" || echo "Couldn't find $selected_file"
-	~/.tel/scripts/wal_cols_termux.sh # copy wal generated cols to ~/.termux/colors.properties
-	#am broadcast --user 0 -a com.termux.app.reload_style com.termux > /dev/null 2>&1 # reload cols in termux
-	status_running=$(pgrep -f status_manager.py)
-	if [ ! -z "$status_running" ] ; then
-		~/.tel/scripts/status_manager/toggle_ui.sh
-		#sleep 0.7	
-		#~/.tel/scripts/status_manager/toggle_ui.sh
-	fi
-	tel-restart
-	printf "\e[33;5;2m Theme\e[m%s press enter to restart + apply changes..\n"
-	read 
-	tel-restart
-fi
+	~/.tel/scripts/apply_colors.sh # copy wal generated cols to ~/.termux/colors.properties
+	restart_tel
 
+	}
+
+main(){
+	case "$1" in
+		-a | --apply)
+			shift
+			apply_theme
+			exit 0
+		;;
+		-f | --file)
+			shift
+			auto_theme
+			exit 0
+		;;
+		-i | --install)
+			install_theme
+			exit 0
+		;;
+		-c | --create)
+			create_theme
+			#read WAL wallpaper
+			exit 0
+		;;
+		# Display the help message
+		-h | --help)
+			show_help
+			exit 0
+		;;
+	esac
+file_search="$@"
+selected_file=$(fzf -e --cycle --color=16 --query="$file_search" --prompt="Pick a file to theme from: " --select-1)
+
+}
