dialer can now take number as input

diff --git a/tel-dialer b/tel-dialer
--- a/tel-dialer
+++ b/tel-dialer
@@ -99,30 +99,34 @@ main() {
     # fuzzy search in $contactsfile to get the number and
     # name in the format
     # Name | Number
-    fzf_output=$(fzf --print-query --cycle --color=16 --prompt=" Call: " --query="$*" --select-1 -0 < "$contactsfile")
-    IFS=$'\n' read -d '' -r -a selected_contact <<< "$fzf_output"
-    if [ ${#selected_contact[@]} -gt 1 ] ; then
-	   unknown_number=${selected_contact[0]}
-	   contact="${selected_contact[1]}"
-   else
-	   contact="${selected_contact[0]}"
-    fi
+	fzf_output=$(fzf --print-query --cycle --color=16 --prompt=" Call: " --query="$*" --select-1 -0 < "$contactsfile")
+	IFS=$'\n' read -d '' -r -a selected_contact <<< "$fzf_output"
+	if [ ${#selected_contact[@]} -gt 1 ] ; then #no match found assume output is printed number
+		unknown_number=${selected_contact[0]}
+		contact="${selected_contact[1]}"
+	else
+		contact="${selected_contact[0]}"
+	fi
     case "$?" in
         	# No contact found
         "1"  )
-		if [ ${#unknown_number} -gt 2 ] ; then
-			#fail to get matching contact trying calling number
-			printf  "\e[38;5;2m Calling:\e[m %s\n"\
-			"[${unknown_number}]"
-			termux-telephony-call "${unknown_number}"
+		if [ ${#selected_contact[@]} -gt 0 ] ; then #no match found assume output is printed number
+			if [ ${#unknown_number} -gt 2 ] ; then
+				#fail to get matching contact trying calling number
+				printf  "\e[38;5;2m Calling:\e[m %s\n"\
+				"[${unknown_number}]"
+				termux-telephony-call "${unknown_number}"
+			fi
+			#printf  "\e[38;5;2m Dialer\e[m: \e[38;5;1mContact not found%s\n\e[m"
+			exit 1
+		else 
+			exit 1
 		fi
-    		#printf  "\e[38;5;2m Dialer\e[m: \e[38;5;1mContact not found%s\n\e[m"
-		exit 1
         ;;
 
         # If Ctrl+C is used 
         "130")
-            return 1
+            exit 1
         ;;
 esac
     # get the contact's name
