tel-open can open multiple files

diff --git a/tel-open b/tel-open
--- a/tel-open
+++ b/tel-open
@@ -20,13 +20,15 @@ export FZF_DEFAULT_OPTS="
 bookmarks_file=~/.tel/data/bookmarks 
 global_url=$2
 [[ -e $bookmarks_file ]] || (echo 'https://t-e-l.github.io' > ${bookmarks_file} ; echo -n 'https://wiki.termux.com/wiki/Main_Page' >> ${bookmarks_file}) # create new list if none exists)
+
+files_to_open=()
 show_help(){
     printf  "%s\n"\
             "Opens a file or link in external app"\
             "tel-open [OPTIONS] [PATTERN]"\
             "__________________________"\                                              "OPTIONS"\
-            "  -h   display this help message"\
-            "  -u https://www.github.com  Open github in android browser"\
+            "  -h   				display this help message"\
+            "  -u https://www.github.com 	 Open github in android browser"\
             "  -u   Open url picker"
 }
 open_url(){
@@ -48,7 +50,8 @@ open_url(){
 }
 
 if [ -z $1 ] ; then
-	selected_file=$(fzf --cycle --color=16 --prompt=" Open in app: ")
+	selected_files=$(fd --type f | fzf -m -d -e --cycle --color=16 --prompt="Select files(s) (with tab key) to open with app: ")
+	IFS=$'\n' read -d '' -r -a files_to_open <<<"$selected_files"
 else
 	case "$1" in
 		-u) #open url in app instead of file
@@ -62,20 +65,27 @@ else
  	esac
 
 	file_search="$@"
-	selected_file="$(fzf -e --cycle --color=16 --query="$file_search" --prompt=" Open in app: " --select-1)"
+ 
+	selected_files=$(fd --type f | fzf -m -d -e --cycle -q "$file_search" --color=16 --prompt="Select (tab key) to Open: ")
+	IFS=$'\n' read -d '' -r -a files_to_open <<<"$selected_files"
 fi
 
-if [ -z "$selected_file" ] ; then
-#	echo 'No file chosen - Exiting...'
+
+if [ -z "${files_to_open}" ] ; then
+	echo 'No files chosen - Exiting...'
 	exit 1
 else
 	curr_dir=$(pwd)
-	printf "\e[38;5;2m Opening\e[m%s file: $curr_dir/$selected_file"
-
-	if [ $(uname -o) == 'Android' ] ; then
-		termux-open "$selected_file" || echo "Couldn't open $selected_file"
-	else
-		mimeopen -n "$selected_file" || echo "Couldn't open $selected_file"
-	fi
+	printf "\e[38;5;2m Opening\e[m%s: "
+	for filename in "${files_to_open[@]}"
+	do
+		echo -ne "$curr_dir/$filename\n"
+		if [ $(uname -o) == 'Android' ] ; then
+			termux-open "$filename" || echo "Couldn't open $selected_file"
+		else
+			(mimeopen -n "$filename" > /dev/null 2>&1) > /dev/null & 
+			#xdg-open "$selected_file" || echo "Couldn't open $selected_file"
+		fi
+	done	
 fi
 
