add wallpaper flag to theme

diff --git a/tel-theme b/tel-theme
--- a/tel-theme
+++ b/tel-theme
@@ -115,7 +115,7 @@ wal_theme(){
 		if [ ! -z $@ ] ; then 
 			cp -f ~/.cache/wal/colors.sh ~/.tel/theme/active/
 			~/.tel/scripts/apply_colors.sh # propagate colors
-			restart_tel
+		#	restart_tel
 		fi
 }
 
@@ -140,6 +140,32 @@ apply_theme(){
 	printf "\n\e[33;5;2m Theme\e[m%s finished applying: $selected_file "
 	restart_tel
 	}
+
+apply_wallpaper(){
+	FZF_DEFAULT_OPTS="
+--info=inline
+--multi
+--preview-window=up:60%:follow:sharp
+--preview '([[ -f {} ]] && (termimage --size=35x35 {} || bat --theme=base16 --style=numbers --color=always {} || cat {})) || ([[ -d {} ]] && (tree -C {} | less)) || echo {} 2> /dev/null | head -200'
+--prompt='∼ ' --pointer='>' --marker='✓'
+--bind '?:toggle-preview'
+--bind 'ctrl-a:select-all'
+--bind 'ctrl-y:execute-silent(echo {+} | pbcopy)'
+"
+	cd ~
+	if [ -z "$@" ] ; then
+		file_search="$@" 
+	else
+		file_search=".jpg"
+	fi
+	selected_file=$(fd --extension=jpg -e png --follow --absolute-path --type f | fzf --color=16 --query="$file_search" --prompt="Pick a image to set as wallpaper: " --select-1)
+	if [ -z $selected_file ] ; then
+		exit 1
+	fi
+
+	printf "\n\e[33;5;2m Theme\e[m%s applying wallpaper: $selected_file "
+	termux-wallpaper $options "$selected_file" || echo "Failed to apply $selected_file"
+}
 
 main(){
 	case "$1" in
@@ -171,7 +197,11 @@ main(){
 			wal_theme "$@"
 			exit 0
 		;;
-
+		-w | --wallpaper)
+			shift
+			apply_wallpaper "$@"
+			exit 0
+		;;
 		# Display the help message
 		-h | --help)
 			show_help
