tel-open support xdg-open on other than android

diff --git a/tel-open b/tel-open
--- a/tel-open
+++ b/tel-open
@@ -17,7 +17,7 @@ export FZF_DEFAULT_OPTS="
 "
 bookmarks_file=~/.tel/data/bookmarks 
 global_url=$2
-[[ -e $bookmarks_file ]] || (echo 'https://t-e-l.github.io' > ${bookmarks_file} ; echo 'https://wiki.termux.com/wiki/Main_Page' >> ${bookmarks_file}) # create new list if none exists)
+[[ -e $bookmarks_file ]] || (echo 'https://t-e-l.github.io' > ${bookmarks_file} ; echo -n 'https://wiki.termux.com/wiki/Main_Page' >> ${bookmarks_file}) # create new list if none exists)
 show_help(){
     printf  "%s\n"\
             "Opens a file or link in external app"\
@@ -34,8 +34,12 @@ open_url(){
 		url=$(cat $bookmarks_file | fzf -e --cycle --color=16 --prompt=" Pick a URL to open with an android app:" --select-1)
 	fi
 	if [ ! -z $url ] ; then
-	termux-open-url $url
-	printf "\e[38;5;2m Opening\e[m%s URL: $url" 
+		if [ $(uname -o) == 'Android' ] ; then
+			termux-open-url "$url"
+		else
+			xdg-open "$url"
+		fi	
+		printf "\e[38;5;2m Opening\e[m%s URL: $url" 
 	else
 		exit 1
 	fi
@@ -65,6 +69,11 @@ if [ -z "$selected_file" ] ; then
 else
 	curr_dir=$(pwd)
 	printf "\e[38;5;2m Opening\e[m%s file: $curr_dir/$selected_file"
-	termux-open "$selected_file" || echo "Couldn't open $selected_file"
+
+	if [ $(uname -o) == 'Android' ] ; then
+		termux-open "$selected_file" || echo "Couldn't open $selected_file"
+	else
+		xdg-open "$selected_file" || echo "Couldn't open $selected_file"
+	fi
 fi
 
